### ISSUE TITLE
HTTP Error 400. The request hostname is invalid.

### ISSUE THREAD

**Issue by planbsim** [plumber-sc/plumber-sc#20]
I have everything configured as you mentioned it in the part [Using IIS](https://github.com/ewerkman/plumber-sc#using-iis) and downloaded the [release.zip](https://github.com/ewerkman/plumber-sc/releases). I configured everything with the default values like IIS-Bindings "http:*:8080:plumber-sc", SitecoreIdentityServer with an additional [Plumber-Client](https://github.com/ewerkman/plumber-sc#configuring-sitecore-identity-server) and the AllowedOrigins for the Sitecore.Commerce.Server [http://localhost:8080](https://github.com/ewerkman/plumber-sc#configuring-your-commerce-engine), but it did not work as expected. Can anybody give me an advise?

Thanks for your support in advance

![bad-request](https://user-images.githubusercontent.com/15728035/41282145-a1b5b99a-6e33-11e8-8d25-d8121e4c1eb3.png)

**Comment by ewerkman** [comment]
Hi @planbsim and @AfshinZavvar,

Do you get to see the Identity Server login page or doesn't it show up at all?

**Comment by AfshinZavvar** [comment]
Hi @ewerkman 
For me this error happens after login.

**Comment by ewerkman** [comment]
I would like to try to replicate this issue. Can you send me your identity server configuration and your plumber configuration file. You can send it to contact@plumber-sc.com. 
Thanks!

**Comment by ewerkman** [comment]
Ok, I think I know what is happening: change the configuration of identity server for the plumber client. Make sure that where it says: localhost:8080 you change it to plumber-sc:8080 (or whatever the host name and port number is you are using). Then do an `iisreset` and do a hard reload of the plumber-sc site.

Identity server is redirecting to the url's specified in the configuration for that client and if you change the domain from `localhost` to `plumber-sc` it is redirecting to the wrong domain.

Hopefully that should work!

**Comment by AfshinZavvar** [comment]
Thanks Erwin,

I removed plumber-sc:8081from iis and created a new site  (localhost:8081).
Worked !

**Comment by ewerkman** [comment]
Great! I will make some changes to the documentation so it is more clear what you need to change when you want to use a domain name instead of localhost.
